' cores.cls
Public AzulEscuro As Long, AzulEscuro1 As Long, AzulClaro As Long, VerdeEscuro As Long, VerdeClaro As Long, VerdeClaro2 As Long, _
       VerdeClaro3 As Long, VerdeClaro4 As Long, CinzaEscuro As Long, CinzaClaro As Long, VermelhoEscuro As Long, _
       VermelhoClaro As Long, AmareloEscuro As Long, AmareloClaro As Long, Branco As Long, Preto As Long, _
       SemCor As Long

Public Sub Cores()
    AzulEscuro = RGB(7, 79, 105)
    AzulEscuro1 = RGB(70, 180, 220)
    AzulClaro = RGB(221, 235, 247)
    VerdeEscuro = RGB(146, 208, 80)
    VerdeClaro = RGB(218, 242, 208)
    VerdeClaro2 = RGB(200, 230, 180)
    VerdeClaro3 = RGB(150, 210, 110)
    VerdeClaro4 = RGB(80, 160, 40)
    CinzaEscuro = RGB(127, 127, 127)
    CinzaClaro = RGB(217, 217, 217)
    VermelhoEscuro = RGB(190, 35, 35)
    VermelhoClaro = RGB(255, 190, 190)
    AmareloEscuro = RGB(220, 220, 120)
    AmareloClaro = RGB(255, 255, 150)
    Branco = RGB(255, 255, 255)
    Preto = RGB(0, 0, 0)
    SemCor = xlNone
End Sub
